version: '3.7'

services:
  mongodb:
    container_name: mongodb-instance
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: